interface SpellingError {
  word: string;
  start: number;
  end: number;
  suggestions: string[];
}

// Common misspellings and their corrections
const commonMisspellings = new Map([
    ['recieve', ['receive']],
    ['seperate', ['separate']],
    ['occured', ['occurred']],
    ['accomodate', ['accommodate']],
    ['begining', ['beginning']],
    ['definately', ['definitely']],
    ['enviroment', ['environment']],
    ['existance', ['existence']],
    ['grammer', ['grammar']],
    ['immedietly', ['immediately']],
    ['independant', ['independent']],
    ['liason', ['liaison']],
    ['millenium', ['millennium']],
    ['neccessary', ['necessary']],
    ['occassion', ['occasion']],
    ['persistant', ['persistent']],
    ['priviledge', ['privilege']],
    ['recomend', ['recommend']],
    ['relevent', ['relevant']],
    ['succesful', ['successful']],
    ['tommorow', ['tomorrow']],
    ['untill', ['until']],
    ['wierd', ['weird']],
    ['adress', ['address']],
    ['alot', ['a lot']],
    ['amature', ['amateur']],
    ['arguement', ['argument']],
    ['beleive', ['believe']],
    ['calender', ['calendar']],
    ['cemetary', ['cemetery']],
    ['collegue', ['colleague']],
    ['comming', ['coming']],
    ['concious', ['conscious']],
    ['curiousity', ['curiosity']],
    ['dissapear', ['disappear']],
    ['embarass', ['embarrass']],
    ['equiptment', ['equipment']],
    ['exagerate', ['exaggerate']],
    ['febuary', ['February']],
    ['freind', ['friend']],
    ['guage', ['gauge']],
    ['happenned', ['happened']],
    ['hieght', ['height']],
    ['jewelery', ['jewelry']],
    ['knowlege', ['knowledge']],
    ['liscense', ['license']],
    ['maintainance', ['maintenance']],
    ['medeval', ['medieval']],
    ['miniscule', ['minuscule']],
    ['mispell', ['misspell']],
    ['neice', ['niece']],
    ['noticable', ['noticeable']],
    ['occurence', ['occurrence']],
    ['parliment', ['parliament']],
    ['publically', ['publicly']],
    ['questionaire', ['questionnaire']],
    ['reciept', ['receipt']],
    ['rythm', ['rhythm']],
    ['secratary', ['secretary']],
    ['sponser', ['sponsor']],
    ['strenght', ['strength']],
    ['tatoo', ['tattoo']],
    ['teh', ['the']],
    ['threshhold', ['threshold']],
    ['vaccum', ['vacuum']],
    ['volcanoe', ['volcano']],
    ['wierd', ['weird']],
    ['acquaintence', ['acquaintance']],
    ['agression', ['aggression']],
    ['beaurocracy', ['bureaucracy']],
    ['caffiene', ['caffeine']],
    ['definate', ['definite']],
    ['dissapoint', ['disappoint']],
    ['ecstacy', ['ecstasy']],
    ['existance', ['existence']],
    ['foriegn', ['foreign']],
    ['goverment', ['government']],
    ['humerous', ['humorous']],
    ['indespensible', ['indispensable']],
    ['inteligent', ['intelligent']],
    ['judgement', ['judgment']],
    ['manouver', ['maneuver']],
    ['occurance', ['occurrence']],
    ['pharoah', ['pharaoh']],
    ['pronounciation', ['pronunciation']],
    ['reccommend', ['recommend']],
    ['seige', ['siege']],
    ['suprise', ['surprise']],
    ['tomatos', ['tomatoes']],
    ['wierd', ['weird']],
    ['yeild', ['yield']],
    ['acclerate', ['accelerate']],
    ['achive', ['achieve']],
    ['addtional', ['additional']],
    ['affraid', ['afraid']],
    ['aggresive', ['aggressive']],
    ['alchohol', ['alcohol']],
    ['anual', ['annual']],
    ['arguement', ['argument']],
    ['assasin', ['assassin']],
    ['awefull', ['awful']],
    ['begining', ['beginning']],
    ['buisness', ['business']],
    ['burgler', ['burglar']],
    ['carreer', ['career']],
    ['catagory', ['category']],
    ['changeing', ['changing']],
    ['collectable', ['collectible']],
    ['comitted', ['committed']],
    ['commitee', ['committee']],
    ['concensus', ['consensus']],
    ['congradulate', ['congratulate']],
    ['consciencious', ['conscientious']],
    ['dependant', ['dependent']],
    ['dissaprove', ['disapprove']],
    ['embarassed', ['embarrassed']],
    ['enviromental', ['environmental']],
    ['exagerated', ['exaggerated']],
    ['exerpt', ['excerpt']],
    ['facillitate', ['facilitate']],
    ['farenheit', ['Fahrenheit']],
    ['fourty', ['forty']],
    ['harrass', ['harass']],
    ['heirarchy', ['hierarchy']],
    ['ignoranus', ['ignoramus']],
    ['imposter', ['impostor']],
    ['independance', ['independence']],
    ['interupt', ['interrupt']],
    ['irresistable', ['irresistible']],
    ['jist', ['gist']],
    ['labratory', ['laboratory']],
    ['legitamate', ['legitimate']],
    ['lightening', ['lightning']],
    ['millitary', ['military']],
    ['mischeivous', ['mischievous']],
    ['misfortunetly', ['unfortunately']],
    ['morgage', ['mortgage']],
    ['neccessity', ['necessity']],
    ['oppinion', ['opinion']],
    ['parralel', ['parallel']],
    ['permanant', ['permanent']],
    ['playwrite', ['playwright']],
    ['potatos', ['potatoes']],
    ['prefered', ['preferred']],
    ['proffesor', ['professor']],
    ['pronounciation', ['pronunciation']],
    ['quarentine', ['quarantine']],
    ['rediculous', ['ridiculous']],
    ['religeous', ['religious']],
    ['remeber', ['remember']],
    ['resistence', ['resistance']],
    ['resturant', ['restaurant']],
    ['rythem', ['rhythm']],
    ['sacreligious', ['sacrilegious']],
    ['satelite', ['satellite']],
    ['seperately', ['separately']],
    ['singlular', ['singular']],
    ['speach', ['speech']],
    ['sucess', ['success']],
    ['tariff', ['tariff']],
    ['tendancy', ['tendency']],
    ['terretory', ['territory']],
    ['tradgedy', ['tragedy']],
    ['truley', ['truly']],
    ['twelth', ['twelfth']],
    ['unforseen', ['unforeseen']],
    ['vacinity', ['vicinity']],
    ['wich', ['which']],
    ['writting', ['writing']],
]);

export function checkSpelling(text: string): SpellingError[] {
  const errors: SpellingError[] = [];
  const words = text.match(/\b\w+\b/g) || [];

  words.forEach(word => {
    const lowerWord = word.toLowerCase();
    if (commonMisspellings.has(lowerWord)) {
      const start = text.indexOf(word);
      errors.push({
        word,
        start,
        end: start + word.length,
        suggestions: commonMisspellings.get(lowerWord) || []
      });
    }
  });

  return errors;
}