export const patterns = {
  passiveVoice: /\b(am|is|are|was|were|be|been|being)\s+\w+ed\b/gi,
  complexWords: /\b(utilize|facilitate|leverage|implement|demonstrate|aforementioned|commence|terminate|ameliorate|ascertain|expedite|perceive|endeavor|articulate)\b/gi,
  redundantPhrases: /\b(absolutely essential|advance planning|basic necessities|close proximity|end result|future plans|past history|unexpected surprise|final outcome|personal opinion|mutual agreement|true fact|completely destroyed|free gift)\b/gi,
  transitionWords: /\b(however|therefore|furthermore|moreover|consequently|additionally|nevertheless|meanwhile|nonetheless|subsequently|alternatively|similarly|hence)\b/gi,
  weakWords: /\b(very|really|quite|basically|actually|just|maybe|stuff|things|kind of|sort of|somewhat|pretty much|a bit|a lot|little)\b/gi,
  wordyPhrases: /\b(in order to|due to the fact that|in spite of the fact that|on account of|in the event that|at this point in time|for the purpose of|with regard to|on the basis of|by means of|in light of|owing to the fact that|with the exception of)\b/gi,
  repeatedWords: /\b(\w+)\b(?:\s+\w+){0,3}\s+\b\1\b/gi,
  spellingErrors: /\b(recieve|seperate|occured|accomodate|definately|enviroment|existance|grammer|immedietly|independant|liason|millenium|neccessary|occassion|persistant|priviledge|recomend|relevent|succesful|tommorow|untill|wierd|adress|alot|amature|arguement|beleive|calender|cemetary|collegue|comming|concious|curiousity|dissapear|embarass|equiptment|exagerate|febuary|freind|guage|happenned|hieght|jewelery|knowlege|liscense|maintainance|medeval|miniscule|mispell|neice|noticable|occurence|parliment|publically|questionaire|reciept|rythm|secratary|sponser|strenght|tatoo|teh|threshhold|vaccum|volcanoe|wierd)\b/gi,
  overusedAdverbs: /\b(quickly|slowly|silently|loudly|happily|sadly|angrily|easily|badly|barely|clearly|nearly|obviously|seriously|simply|totally|utterly)\b/gi,
  cliches: /\b(at the end of the day|better late than never|last but not least|time will tell|in the nick of time|hit the nail on the head|take it with a grain of salt|easier said than done|think outside the box|what goes around comes around|back to square one)\b/gi,
  vagueWords: /\b(stuff|things|something|anything|everything|nothing|someone|anyone|everyone|thing)\b/gi,
  informalLanguage: /\b(gonna|wanna|kinda|sorta|ain't|lemme|gotta|y'all|dunno|gimme|tryna|coulda|woulda|shoulda|yup|nah)\b/gi,
  splitInfinitives: /\b(to\s+quickly|to\s+slowly|to\s+carefully|to\s+deliberately|to\s+boldly)\b/gi,
  unclearPronouns: /\b(it|this|that|these|those|which|what|who|whose|whom)\b(?=\s+\w+)/gi,
  sentenceStarters: /\b(So|And|But|Because|Or|Then|Although|Though|Well|Besides|Meanwhile|However|Therefore|Moreover|Nevertheless|Additionally|Firstly|Secondly|Finally)\b/gi,
  longSentences: /^(.{100,})$/gm,
  shortSentences: /^(.{0,5})$/gm,
  contractions: /\b(\w+n't|'ll|'ve|'re|'s|'d|'m)\b/gi,
  pronouns: /\b(I|me|you|he|she|it|we|us|they|them|my|your|his|her|its|our|their|mine|yours|hers|ours|theirs|myself|yourself|himself|herself|itself|ourselves|themselves)\b/gi,
  excessivePunctuation: /([!?.]){2,}/g,
  serialComma: /, and /g,
  missingOxfordComma: /, (\w+\s+and\s+\w+)/g,
  improperCapitalization: /\b([a-z]{1})([A-Z])/g,
  danglingModifiers: /\b(Driving down the street|Walking into the room|After finishing the exam|Looking around the park|Running up the stairs|While cooking dinner|When watching the movie|While talking to friends)\b/gi,
  inconsistentVerbTense: /\b(was|is|are|were|been|being|am)\s+(\w+ing)\b/g,
  homophones: /\b(accept|except|affect|effect|than|then|to|too|two|there|their|they're|its|it's|your|you're|complement|compliment|principal|principle|stationary|stationery|lose|loose|led|lead|capital|capitol)\b/gi,
  parallelStructureErrors: /\b(\w+ing\s+and\s+\w+ing|\w+ed\s+and\s+\w+ed)\b/gi,
  capitalizationErrors: /\b(the|a|an|but|and|for|or|nor|yet|so|to|as|at|by|in|of|on|per|than|up|via|with)\b(?=\s[A-Z])/g,
};
